If:
  PathMatch: [.*\.cpp, .*\.hpp, .*\.cc, .*\.hh]
CompileFlags:
  Add: [-std=c++23]
---
If:
  PathMatch: [.*\.c, .*\.h]
CompileFlags:
  Add: [-xc, -std=c17]
---
Index:
  Background: Build

Style:
  BasedOnStyle: LLVM
  IndentWidth: 4
  SpaceBeforeAssignmentOperators: true
  SpaceBeforeParens: ControlStatements

Diagnostics:
  UnusedIncludes: Strict
  HeaderInsertion: Never
